export default ROUTERS = {
  // SPLASH: 'splash',
  INTRO_CMS: 'introcms',
  INTRO_HEALTH: 'introhealth',
  INTRO_VIDEO: 'introvideo',
  INTRO_SMARTER: 'introsmarter',
  INTRO_OAM: 'introoam',
  INTRO_WELCOME: 'welcome',

  LOGIN: 'login',

  HOME_TAB: 'hometab',
  HOME_NAVIGATOR: 'homenavi',

  HEALTH: 'health',
  HEALTH_STACK: 'healthstack',
  HEALTH_SITES: 'healthsites',
  HEALTH_DETAIL: 'healthdetail',
  HEALTH_ALERTS: 'healthalerts',
  HEALTH_ALERT_DETAIL: 'healthalertsdetail',

  VIDEO: 'video',
  VIDEO_STACK: 'videostack',
  VIDEO_REGIONS: 'videoregions',
  VIDEO_SITES: 'videosites',
  VIDEO_NVRS: 'videonvr',
  VIDEO_CHANNELS: 'videochannels',
  VIDEO_CHANNELS_SETTING: 'videochannelssetting',
  VIDEO_PLAYER: 'videoplayer',
  // VIDEO_LIVE: 'videolive',
  // VIDEO_SEARCH: 'videosearch',

  ALARM: 'alarm',
  ALARM_STACK: 'alarmstack',
  ALARM_LIVE_STACK: 'alarmlivestack',
  ALARM_LIVE: 'alarmlive',
  ALARM_SEARCH: 'alarmsearch',
  ALARM_DETAIL: 'alarmdetail',
  ALARM_SEARCH_DETAIL: 'alarmsearchdetail',

  OAM: 'oam',
  OAM_STACK: 'oamstack',
  OAM_SITES: 'oam',
  OAM_DETAIL: 'oamdetail',

  POS: 'pos',
  POS_STACK: 'posstack',
  TRANSACTIONS: 'trans',
  TRAN_DETAIL: 'trandetail',
  TRAN_DETAIL_FCM: 'trandetailFCM',

  OPTIONS: 'options',
  OPTIONS_NAVIGATOR: 'optionsnavi',
  OPTIONS_PROFILE: 'optionsprofile',
  OPTIONS_ABOUT: 'optionsabout',
  OPTIONS_NOTIFY: 'optionsnotify',
  OPTIONS_VIDEO: 'optionsvideo',
  // OPTIONS_LOGOUT: 'optionslogout',
};
